# Generated by Django 3.2.16 on 2022-12-29 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wines', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wines.wine')),
            ],
            options={
                'ordering': ['created_on'],
                'unique_together': {('owner', 'wine')},
            },
        ),
    ]
