# Generated by Django 3.2.16 on 2022-12-29 13:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('vintage', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), wines.models.max_value_current_year])),
                ('producer', models.CharField(max_length=300)),
                ('grapes', models.CharField(blank=True, max_length=255)),
                ('tasting_day', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('wine_type_choice', models.CharField(choices=[('Red wine', 'Red wine'), ('White wine', 'White wine'), ('Sparkling wine', 'Sparkling wine'), ('Other', 'Other')], default='Red wine', max_length=45)),
                ('img', models.ImageField(default='../default_wine_b693ou', upload_to='images/')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='Rate your wine', max_length=5)),
                ('owner', models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
