# Generated by Django 3.2.16 on 2022-12-29 10:56

import django.core.validators
from django.db import migrations, models
import wines.models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='year',
            new_name='tasting_day',
        ),
        migrations.AddField(
            model_name='wine',
            name='vintage',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), wines.models.max_value_current_year]),
        ),
    ]
